import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminRouter from "./admin";
import billingRouter from "./billing";
import clientsRouter from "./clients";
import screensRouter from "./screens";
import mediaRouter from "./media";
import playlistsRouter from "./playlists";
import schedulesRouter from "./schedules";
import dashboardRouter from "./dashboard";
import playerRouter from "./player";
import storageRouter from "./storage";
import reportsRouter from "./reports";
import operatorsRouter from "./operators";
import monitoringRouter from "./monitoring";
import screenGroupsRouter from "./screen-groups";
import emergencyRouter from "./emergency";
import totpRouter from "./totp";
import devicesRouter from "./devices";
import rssRouter from "./rss";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use("/admin", adminRouter);
router.use(billingRouter);
router.use("/clients", clientsRouter);
router.use("/screens", screensRouter);
router.use("/screen-groups", screenGroupsRouter);
router.use("/media", mediaRouter);
router.use("/playlists", playlistsRouter);
router.use("/schedules", schedulesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/player", playerRouter);
router.use("/reports", reportsRouter);
router.use("/operators", operatorsRouter);
router.use("/monitoring", monitoringRouter);
router.use("/emergency", emergencyRouter);
router.use("/auth/totp", totpRouter);
router.use("/devices", devicesRouter);
router.use(rssRouter);

export default router;
